### ISSUE TITLE
Demo is down.

### ISSUE THREAD

**Issue by x-N0** [alfonsobries/vue-tailwind-themes#8]
I'm interested into your project, but I'd like to see the demo.
I think is something I had on mind, so I don't want to redo the wheel.

Que tengas un buen día, carnal. / Have a great day, buddy.

**Comment by alfonsobries** [comment]
@x-N0 Sorry I didn't notice your comment until now what demo do you refer, maybe is not down anymore?

Gracias!

**Comment by alfonsobries** [comment]
I'm gonna close this issue for now since I am not able to replicate and is a little old, maybe was something temporal, feel free to open it again if you think I am wrong, thanks!
